using System;
using UnityEditor;
using UnityEditor.Build;
using UnityEngine;
using UnityEngine.iOS;

namespace SoraTehk.BuildTool {
/* Generated by Claude AI
 * UNITY 6.3 (6000.3) PlayerSettings API Reference
 *
 * This comprehensive list documents all PlayerSettings properties and methods
 * available for scripting in Unity 6.3.
 *
 * Properties marked with [READ-ONLY] cannot be modified via code
 * Properties marked with [UI-ONLY] are only settable through the Unity Editor UI
 */
    public class MementoPlayerSettings {
        #region GENERAL / CROSS-PLATFORM PROPERTIES (Can be adjusted via code)
        public static void SetGeneralSettings() {
            // ===== PRODUCT INFORMATION =====
            PlayerSettings.productName = "MyGame";
            PlayerSettings.companyName = "MyCompany";
            PlayerSettings.bundleVersion = "1.0.0";

            // [READ-ONLY] - Generated automatically, cannot be set
            // string guid = PlayerSettings.productGUID;

            // ===== RESOLUTION AND DISPLAY =====
            PlayerSettings.defaultScreenWidth = 1920;
            PlayerSettings.defaultScreenHeight = 1080;
            PlayerSettings.defaultWebScreenWidth = 960;
            PlayerSettings.defaultWebScreenHeight = 600;
            PlayerSettings.fullScreenMode = FullScreenMode.FullScreenWindow;
            PlayerSettings.resizableWindow = true;
            PlayerSettings.allowFullscreenSwitch = true;
            PlayerSettings.resetResolutionOnWindowResize = false;
            PlayerSettings.visibleInBackground = true;
            PlayerSettings.use32BitDisplayBuffer = true;
            PlayerSettings.useHDRDisplay = false;
            PlayerSettings.allowHDRDisplaySupport = false;
            PlayerSettings.hdrBitDepth = HDRDisplayBitDepth.BitDepth10;

            // ===== CURSOR =====
            // PlayerSettings.defaultCursor = myCursorTexture;
            PlayerSettings.cursorHotspot = new Vector2(0, 0);

            // ===== ORIENTATION (MOBILE) =====
            PlayerSettings.defaultInterfaceOrientation = UIOrientation.AutoRotation;
            PlayerSettings.allowedAutorotateToPortrait = true;
            PlayerSettings.allowedAutorotateToPortraitUpsideDown = true;
            PlayerSettings.allowedAutorotateToLandscapeLeft = true;
            PlayerSettings.allowedAutorotateToLandscapeRight = true;
            PlayerSettings.useAnimatedAutorotation = false;

            // ===== STATUS BAR (iOS only) =====
            PlayerSettings.statusBarHidden = true;

            // ===== COLOR SPACE =====
            PlayerSettings.colorSpace = ColorSpace.Linear;

            // ===== GRAPHICS =====
            PlayerSettings.graphicsJobs = true;
            PlayerSettings.graphicsJobMode = GraphicsJobMode.Native;
            PlayerSettings.gpuSkinning = true; // Deprecated - use meshDeformation instead
            PlayerSettings.meshDeformation = MeshDeformation.GPU;
            PlayerSettings.MTRendering = true;

            // ===== RENDERING =====
            PlayerSettings.stereoRenderingPath = StereoRenderingPath.SinglePass;
            PlayerSettings.enable360StereoCapture = false;

            // ===== AUDIO =====
            PlayerSettings.muteOtherAudioSources = false;
            PlayerSettings.audioSpatialExperience = AudioSpatialExperience.Bypassed;

            // ===== RUNTIME =====
            PlayerSettings.runInBackground = true;
            PlayerSettings.forceSingleInstance = false;

            // ===== OPTIMIZATION =====
            PlayerSettings.bakeCollisionMeshes = false;
            PlayerSettings.stripUnusedMeshComponents = false;
            PlayerSettings.stripEngineCode = true;
            PlayerSettings.strictShaderVariantMatching = false;
            PlayerSettings.dedicatedServerOptimizations = false;

            // ===== MEMORY =====
            PlayerSettings.gcIncremental = true;

            // ===== NETWORKING =====
            PlayerSettings.insecureHttpOption = InsecureHttpOption.NotAllowed;

            // ===== PROFILING & DEBUGGING =====
            PlayerSettings.enableInternalProfiler = false;
            PlayerSettings.enableFrameTimingStats = false;
            PlayerSettings.enableCrashReportAPI = true;
            PlayerSettings.usePlayerLog = true;
            PlayerSettings.logObjCUncaughtExceptions = true;

            // ===== VALIDATION =====
            PlayerSettings.enableMetalAPIValidation = false;
            PlayerSettings.enableOpenGLProfilerGPURecorders = false;

            // ===== OPENGL =====
            PlayerSettings.openGLRequireES31 = false;
            PlayerSettings.openGLRequireES31AEP = false;
            PlayerSettings.openGLRequireES32 = false;

            // ===== VULKAN =====
            PlayerSettings.vulkanEnableSetSRGBWrite = false;
            PlayerSettings.vulkanEnablePreTransform = false;
            PlayerSettings.vulkanEnableLateAcquireNextImage = false;
            PlayerSettings.vulkanNumSwapchainBuffers = 3;

            // ===== D3D12 =====
            // PlayerSettings.d3D12DeviceFilterListAsset = myAsset;
            PlayerSettings.useFlipModelSwapchain = true;

            // ===== PLATFORM SPECIFIC (GENERAL) =====
            PlayerSettings.macRetinaSupport = true;
            PlayerSettings.preserveFramebufferAlpha = false;
            PlayerSettings.windowsGamepadBackendHint = WindowsGamepadBackendHint.WindowsGamepadBackendHintDefault;

            // ===== LEGACY =====
            PlayerSettings.legacyClampBlendShapeWeights = false;

            // ===== SPRITE BATCHING =====
            PlayerSettings.spriteBatchVertexThreshold = 300;

            // ===== MIP STRIPPING =====
            PlayerSettings.mipStripping = false;

            // ===== SPLASH SCREEN =====
            // PlayerSettings.virtualRealitySplashScreen = mySplashTexture;

            // ===== BUNDLE VERSIONS (PLATFORM SPECIFIC) =====
            PlayerSettings.tvOSBundleVersion = "1.0";
            PlayerSettings.visionOSBundleVersion = "1.0";

            // ===== ACCELEROMETER =====
            PlayerSettings.accelerometerFrequency = 60;

            // ===== MAC APP STORE =====
            PlayerSettings.useMacAppStoreValidation = false;

            // ===== ADVANCED LICENSE =====
            // [READ-ONLY] - Cannot be set via code
            // bool hasAdvanced = PlayerSettings.advancedLicense;

            // ===== COMPILER =====
            PlayerSettings.allowUnsafeCode = false;
            PlayerSettings.suppressCommonWarnings = false;
        }
        #endregion

        #region METHODS FOR PLATFORM-SPECIFIC SETTINGS
        public static void SetPlatformSpecificSettings() {
            NamedBuildTarget androidTarget = NamedBuildTarget.Android;
            NamedBuildTarget iosTarget = NamedBuildTarget.iOS;
            NamedBuildTarget standaloneTarget = NamedBuildTarget.Standalone;

            // ===== APPLICATION IDENTIFIER =====
            PlayerSettings.SetApplicationIdentifier(androidTarget, "com.company.app");
            PlayerSettings.SetApplicationIdentifier(iosTarget, "com.company.app");
            string identifier = PlayerSettings.GetApplicationIdentifier(androidTarget);
            // Can also use: PlayerSettings.applicationIdentifier (for current platform)

            // ===== SCRIPTING =====
            PlayerSettings.SetScriptingBackend(androidTarget, ScriptingImplementation.IL2CPP);
            ScriptingImplementation backend = PlayerSettings.GetScriptingBackend(androidTarget);
            ScriptingImplementation defaultBackend = PlayerSettings.GetDefaultScriptingBackend(androidTarget);

            // ===== API COMPATIBILITY =====
            PlayerSettings.SetApiCompatibilityLevel(androidTarget, ApiCompatibilityLevel.NET_Unity_4_8);
            ApiCompatibilityLevel apiLevel = PlayerSettings.GetApiCompatibilityLevel(androidTarget);
            PlayerSettings.SetEditorAssembliesCompatibilityLevel(EditorAssembliesCompatibilityLevel.NET_Unity_4_8);
            EditorAssembliesCompatibilityLevel editorLevel = PlayerSettings.GetEditorAssembliesCompatibilityLevel();

            // ===== ARCHITECTURE =====
            PlayerSettings.SetArchitecture(androidTarget, 1); // 0 = None, 1 = ARM64, 2 = Universal
            int arch = PlayerSettings.GetArchitecture(androidTarget);

            // ===== GRAPHICS APIs =====
            PlayerSettings.SetUseDefaultGraphicsAPIs(BuildTarget.Android, false);
            bool useDefault = PlayerSettings.GetUseDefaultGraphicsAPIs(BuildTarget.Android);
            PlayerSettings.SetGraphicsAPIs(
                BuildTarget.Android, new UnityEngine.Rendering.GraphicsDeviceType[] {
                    UnityEngine.Rendering.GraphicsDeviceType.Vulkan, UnityEngine.Rendering.GraphicsDeviceType.OpenGLES3
                }
            );
            UnityEngine.Rendering.GraphicsDeviceType[] apis = PlayerSettings.GetGraphicsAPIs(BuildTarget.Android);

            // ===== IL2CPP SETTINGS =====
            PlayerSettings.SetIl2CppCompilerConfiguration(androidTarget, Il2CppCompilerConfiguration.Release);
            Il2CppCompilerConfiguration il2cppConfig = PlayerSettings.GetIl2CppCompilerConfiguration(androidTarget);

            PlayerSettings.SetIl2CppCodeGeneration(androidTarget, Il2CppCodeGeneration.OptimizeSize);
            Il2CppCodeGeneration codeGen = PlayerSettings.GetIl2CppCodeGeneration(androidTarget);

            PlayerSettings.SetIl2CppStacktraceInformation(androidTarget, Il2CppStacktraceInformation.MethodOnly);
            Il2CppStacktraceInformation stackInfo = PlayerSettings.GetIl2CppStacktraceInformation(androidTarget);

            PlayerSettings.SetAdditionalIl2CppArgs("--emit-null-checks");
            string il2cppArgs = PlayerSettings.GetAdditionalIl2CppArgs();

            // ===== MANAGED STRIPPING =====
            PlayerSettings.SetManagedStrippingLevel(androidTarget, ManagedStrippingLevel.High);
            ManagedStrippingLevel stripping = PlayerSettings.GetManagedStrippingLevel(androidTarget);

            // ===== SCRIPTING DEFINES =====
            PlayerSettings.SetScriptingDefineSymbols(androidTarget, "DEBUG;MY_DEFINE");
            string defines = PlayerSettings.GetScriptingDefineSymbols(androidTarget);

            // ===== COMPILER ARGUMENTS =====
            PlayerSettings.SetAdditionalCompilerArguments(
                androidTarget, new string[] {
                    "-warnaserror"
                }
            );
            string[] compilerArgs = PlayerSettings.GetAdditionalCompilerArguments(androidTarget);

            // ===== BATCHING =====
            PlayerSettings.SetStaticBatchingForPlatform(BuildTarget.Android, true);
            bool staticBatch = PlayerSettings.GetStaticBatchingForPlatform(BuildTarget.Android);

            PlayerSettings.SetDynamicBatchingForPlatform(BuildTarget.Android, true);
            bool dynamicBatch = PlayerSettings.GetDynamicBatchingForPlatform(BuildTarget.Android);

            // ===== MOBILE MULTITHREADING =====
            PlayerSettings.SetMobileMTRendering(androidTarget, true);
            bool mobileMT = PlayerSettings.GetMobileMTRendering(androidTarget);

            // ===== NORMAL MAP ENCODING =====
            PlayerSettings.SetNormalMapEncoding(androidTarget, NormalMapEncoding.XYZ);
            NormalMapEncoding normalEncoding = PlayerSettings.GetNormalMapEncoding(androidTarget);

            // ===== SHADER PRECISION =====
            PlayerSettings.SetShaderPrecisionModel(ShaderPrecisionModel.PlatformDefault);
            ShaderPrecisionModel shaderPrecision = PlayerSettings.GetShaderPrecisionModel();

            // ===== STACK TRACE LOGGING =====
            PlayerSettings.SetStackTraceLogType(LogType.Error, StackTraceLogType.ScriptOnly);
            StackTraceLogType logType = PlayerSettings.GetStackTraceLogType(LogType.Error);

            // ===== PRELOADED ASSETS =====
            // PlayerSettings.SetPreloadedAssets(new Object[] { myAsset1, myAsset2 });
            // Object[] assets = PlayerSettings.GetPreloadedAssets();

            // ===== ICONS =====
            // PlayerSettings.SetIcons(androidTarget, new Texture2D[] { icon1, icon2 }, IconKind.Application);
            // Texture2D[] icons = PlayerSettings.GetIcons(androidTarget, IconKind.Application);
            // int[] iconSizes = PlayerSettings.GetIconSizes(androidTarget, IconKind.Application);

            // ===== PLATFORM ICONS (ADVANCED) =====
            // PlatformIconKind[] kinds = PlayerSettings.GetSupportedIconKinds(androidTarget);
            // PlatformIcon[] platformIcons = PlayerSettings.GetPlatformIcons(androidTarget, kind);
            // PlayerSettings.SetPlatformIcons(androidTarget, kind, platformIcons);

            // ===== SHADER CHUNK SETTINGS =====
            PlayerSettings.SetDefaultShaderChunkCount(256);
            int chunkCount = PlayerSettings.GetDefaultShaderChunkCount();

            PlayerSettings.SetDefaultShaderChunkSizeInMB(16);
            int chunkSize = PlayerSettings.GetDefaultShaderChunkSizeInMB();

            PlayerSettings.SetOverrideShaderChunkSettingsForPlatform(BuildTarget.Android, true);
            bool overrideChunks = PlayerSettings.GetOverrideShaderChunkSettingsForPlatform(BuildTarget.Android);

            PlayerSettings.SetShaderChunkCountForPlatform(BuildTarget.Android, 512);
            int platformChunkCount = PlayerSettings.GetShaderChunkCountForPlatform(BuildTarget.Android);

            PlayerSettings.SetShaderChunkSizeInMBForPlatform(BuildTarget.Android, 32);
            int platformChunkSize = PlayerSettings.GetShaderChunkSizeInMBForPlatform(BuildTarget.Android);

            // ===== VIRTUAL TEXTURING =====
            PlayerSettings.SetVirtualTexturingSupportEnabled(true);
            bool vtEnabled = PlayerSettings.GetVirtualTexturingSupportEnabled();

            // ===== STARTUP LOGS =====
            PlayerSettings.SetCaptureStartupLogs(androidTarget, true);
            bool captureLogs = PlayerSettings.GetCaptureStartupLogs(androidTarget);

            // ===== TEMPLATE CUSTOM VALUES =====
            PlayerSettings.SetTemplateCustomValue("key", "value");
            string templateValue = PlayerSettings.GetTemplateCustomValue("key");
        }
        #endregion

        #region ANDROID SPECIFIC PROPERTIES (Can be adjusted via code)
        public static void SetAndroidSettings() {
            // ===== BASIC SETTINGS =====
            PlayerSettings.Android.minSdkVersion = AndroidSdkVersions.AndroidApiLevel30;
            PlayerSettings.Android.targetSdkVersion = AndroidSdkVersions.AndroidApiLevel33;
            PlayerSettings.Android.bundleVersionCode = 1;

            // [READ-ONLY]
            // AndroidSdkVersions minSupported = PlayerSettings.Android.minSupportedSdkVersion;

            // ===== WINDOW SETTINGS =====
            PlayerSettings.Android.defaultWindowWidth = 1920;
            PlayerSettings.Android.defaultWindowHeight = 1080;
            PlayerSettings.Android.minimumWindowWidth = 320;
            PlayerSettings.Android.minimumWindowHeight = 180;
            PlayerSettings.Android.resizeableActivity = true;

            // ===== DISPLAY SETTINGS =====
            PlayerSettings.Android.fullscreenMode = FullScreenMode.FullScreenWindow;
            PlayerSettings.Android.startInFullscreen = true;
            PlayerSettings.Android.renderOutsideSafeArea = true;
            PlayerSettings.Android.blitType = AndroidBlitType.Auto;
            PlayerSettings.Android.displayOptions = AndroidDisplayOptions.None;

            // ===== ASPECT RATIO =====
            PlayerSettings.Android.minAspectRatio = 1.5f;
            PlayerSettings.Android.maxAspectRatio = 2.4f;

            // ===== ORIENTATION =====
            PlayerSettings.Android.autoRotationBehavior = AndroidAutoRotationBehavior.User;

            // ===== ARCHITECTURE =====
            PlayerSettings.Android.targetArchitectures = AndroidArchitecture.ARM64;
            PlayerSettings.Android.buildApkPerCpuArchitecture = false;

            // ===== SECURITY =====
            PlayerSettings.Android.enableArmv9SecurityFeatures = false;

            // ===== KEYSTORE (SIGNING) =====
            PlayerSettings.Android.useCustomKeystore = true;
            PlayerSettings.Android.keystoreName = "user.keystore";
            PlayerSettings.Android.keystorePass = "password123";
            PlayerSettings.Android.keyaliasName = "mykey";
            PlayerSettings.Android.keyaliasPass = "keypass123";

            // ===== MINIFICATION =====
            PlayerSettings.Android.minifyDebug = false;
            PlayerSettings.Android.minifyRelease = true;

            // ===== INSTALLATION =====
            PlayerSettings.Android.preferredInstallLocation = AndroidPreferredInstallLocation.Auto;
            PlayerSettings.Android.preferredDataLocation = AndroidPreferredDataLocation.PreferExternal;

            // ===== PERMISSIONS =====
            PlayerSettings.Android.forceInternetPermission = false;
            PlayerSettings.Android.forceSDCardPermission = false;

            // ===== FEATURES =====
            PlayerSettings.Android.androidTVCompatibility = false;
            PlayerSettings.Android.ARCoreEnabled = false;

            // ===== APP CATEGORY =====
            // PlayerSettings.Android.appCategory = AndroidAppCategory.Game;

            // ===== APPLICATION ENTRY =====
            PlayerSettings.Android.applicationEntry = AndroidApplicationEntry.GameActivity;

            // ===== OPTIMIZATION =====
            PlayerSettings.Android.optimizedFramePacing = true;

            // ===== TEXTURE COMPRESSION =====
            PlayerSettings.Android.textureCompressionFormats = new TextureCompressionFormat[] {
                TextureCompressionFormat.ETC2, TextureCompressionFormat.ASTC
            };

            // ===== SPLASH SCREEN =====
            PlayerSettings.Android.splashScreenScale = AndroidSplashScreenScale.Center;
            PlayerSettings.Android.showActivityIndicatorOnLoading = AndroidShowActivityIndicatorOnLoading.Large;

            // ===== BINARY SPLIT =====
            PlayerSettings.Android.splitApplicationBinary = false;

            // ===== DEPTH/STENCIL =====
            PlayerSettings.Android.disableDepthAndStencilBuffers = false;

            // ===== RUNTIME =====
            PlayerSettings.Android.runWithoutFocus = false;

            // ===== GOOGLE PLAY =====
            PlayerSettings.Android.reportGooglePlayAppDependencies = false;

            // ===== BACK BUTTON =====
            PlayerSettings.Android.predictiveBackSupport = false;

            // ===== VULKAN =====
            // PlayerSettings.Android.androidVulkanDeviceFilterListAsset = myFilterAsset;
        }
        #endregion

        #region iOS SPECIFIC PROPERTIES (Can be adjusted via code)
        public static void SetiOSSettings() {
            // ===== BASIC INFO =====
            PlayerSettings.iOS.applicationDisplayName = "MyApp";
            PlayerSettings.iOS.buildNumber = "1";

            // ===== SDK & VERSION =====
            PlayerSettings.iOS.sdkVersion = iOSSdkVersion.DeviceSDK;
            PlayerSettings.iOS.targetOSVersionString = "13.0";
            PlayerSettings.iOS.targetDevice = iOSTargetDevice.iPhoneAndiPad;
            PlayerSettings.iOS.simulatorSdkArchitecture = AppleMobileArchitectureSimulator.ARM64;

            // ===== SIGNING =====
            PlayerSettings.iOS.appleEnableAutomaticSigning = true;
            PlayerSettings.iOS.appleDeveloperTeamID = "TEAM123456";
            PlayerSettings.iOS.iOSManualProvisioningProfileID = "profile-uuid";
            PlayerSettings.iOS.iOSManualProvisioningProfileType = ProvisioningProfileType.Development;
            PlayerSettings.iOS.tvOSManualProvisioningProfileID = "tvos-profile-uuid";
            PlayerSettings.iOS.tvOSManualProvisioningProfileType = ProvisioningProfileType.Development;
            PlayerSettings.iOS.VisionOSManualProvisioningProfileID = "visionos-profile-uuid";
            PlayerSettings.iOS.VisionOSManualProvisioningProfileType = ProvisioningProfileType.Development;

            // ===== URL SCHEMES =====
            PlayerSettings.iOS.iOSUrlSchemes = new string[] {
                "myapp", "myscheme"
            };

            // ===== PRIVACY DESCRIPTIONS =====
            PlayerSettings.iOS.cameraUsageDescription = "This app needs camera access";
            PlayerSettings.iOS.microphoneUsageDescription = "This app needs microphone access";
            PlayerSettings.iOS.locationUsageDescription = "This app needs location access";

            // ===== DISPLAY =====
            PlayerSettings.iOS.statusBarStyle = iOSStatusBarStyle.Default;
            PlayerSettings.iOS.showActivityIndicatorOnLoading = iOSShowActivityIndicatorOnLoading.Large;
            PlayerSettings.iOS.hideHomeButton = false;
            PlayerSettings.iOS.deferSystemGesturesMode = SystemGestureDeferMode.None;

            // ===== ICON =====
            PlayerSettings.iOS.prerenderedIcon = false;

            // ===== MULTITASKING =====
            PlayerSettings.iOS.requiresFullScreen = false;

            // ===== BACKGROUND =====
            PlayerSettings.iOS.appInBackgroundBehavior = iOSAppInBackgroundBehavior.Suspend;
            PlayerSettings.iOS.backgroundModes = iOSBackgroundMode.AudioAirplayPiP | iOSBackgroundMode.LocationUpdates;

            // ===== NETWORKING =====
            PlayerSettings.iOS.requiresPersistentWiFi = false;

            // ===== OPTIMIZATION =====
            PlayerSettings.iOS.scriptCallOptimization = ScriptCallOptimizationLevel.SlowAndSafe;

            // ===== RENDERING =====
            PlayerSettings.iOS.forceHardShadowsOnMetal = false;
            PlayerSettings.iOS.disableDepthAndStencilBuffers = false;

            // ===== ON DEMAND RESOURCES =====
            PlayerSettings.iOS.useOnDemandResources = false;

            // ===== LAUNCH SCREENS =====
            // PlayerSettings.iOS.SetiPhoneLaunchScreenType(iOSLaunchScreenType.ImageAndBackgroundRelative);
            // PlayerSettings.iOS.SetiPadLaunchScreenType(iOSLaunchScreenType.ImageAndBackgroundRelative);
            // PlayerSettings.iOS.SetLaunchScreenImage(iOSLaunchScreenImageType.iPhonePortrait2x, myTexture);
        }
        #endregion

        #region WEBGL SPECIFIC PROPERTIES (Can be adjusted via code)
        public static void SetWebGLSettings() {
            // ===== MEMORY =====
            PlayerSettings.WebGL.memorySize = 512; // Deprecated - use new memory settings
            PlayerSettings.WebGL.memoryGrowthMode = WebGLMemoryGrowthMode.Geometric;
            PlayerSettings.WebGL.initialMemorySize = 256;
            PlayerSettings.WebGL.maximumMemorySize = 2048;
            PlayerSettings.WebGL.linearMemoryGrowthStep = 16;
            PlayerSettings.WebGL.geometricMemoryGrowthStep = 2.0f;
            PlayerSettings.WebGL.memoryGeometricGrowthCap = 96;

            // ===== COMPRESSION =====
            PlayerSettings.WebGL.compressionFormat = WebGLCompressionFormat.Brotli;
            PlayerSettings.WebGL.decompressionFallback = true;
            PlayerSettings.WebGL.nameFilesAsHashes = false;

            // ===== EXCEPTIONS =====
            PlayerSettings.WebGL.exceptionSupport = WebGLExceptionSupport.FullWithStacktrace;
            PlayerSettings.WebGL.wasmArithmeticExceptions = WebGLWasmArithmeticExceptions.Throw;

            // ===== DEBUGGING =====
            PlayerSettings.WebGL.debugSymbolMode = WebGLDebugSymbolMode.Embedded;
            PlayerSettings.WebGL.showDiagnostics = false;

            // ===== CACHING =====
            PlayerSettings.WebGL.dataCaching = true;

            // ===== LINKER =====
            PlayerSettings.WebGL.linkerTarget = WebGLLinkerTarget.Wasm;

            // ===== WEBASSEMBLY FEATURES =====
            PlayerSettings.WebGL.wasm2023 = true;
            PlayerSettings.WebGL.webAssemblyTable = true;
            PlayerSettings.WebGL.webAssemblyBigInt = true;

            // ===== THREADING =====
            PlayerSettings.WebGL.threadsSupport = true;

            // ===== GRAPHICS =====
            PlayerSettings.WebGL.powerPreference = WebGLPowerPreference.Default;

            // ===== TEMPLATE =====
            PlayerSettings.WebGL.template = "PROJECT:Minimal";

            // ===== RUNTIME =====
            PlayerSettings.WebGL.closeOnQuit = false;

            // ===== SUBMODULE STRIPPING =====
            PlayerSettings.WebGL.enableSubmoduleStrippingCompatibility = false;
        }
        #endregion

        #region PROPERTIES THAT CANNOT BE ADJUSTED VIA CODE (UI-ONLY)
        /*
         * ========================================
         * PROPERTIES THAT CANNOT BE SET VIA CODE
         * ========================================
         *
         * The following settings are available in the Player Settings UI but
         * CANNOT be modified programmatically through the PlayerSettings API:
         *
         * 1. ICONS (partial - some icon methods exist but not all formats)
         *    - Default Icon (top-level icon)
         *    - Various platform-specific icon sizes (some accessible via SetIcons/GetIcons)
         *    - Adaptive icons for Android (requires PlatformIcon API)
         *
         * 2. SPLASH SCREENS
         *    - Splash Screen Logo
         *    - Splash Screen Background
         *    - Splash Screen Animation Mode
         *    - Show Unity Logo
         *    - Show Splash Screen (Unity Free/Pro setting)
         *    - Preview (UI visualization only)
         *    - Note: Some splash screen properties exist in code but many are UI-only
         *
         * 3. RESOLUTION AND PRESENTATION (some settings)
         *    - Resolution Dialog Banner (Standalone)
         *    - Supported Aspect Ratios (detailed UI checkboxes)
         *    - Mac App Store Icon (specific to Mac)
         *
         * 4. OTHER SETTINGS (various)
         *    - Color Space (can be set via PlayerSettings.colorSpace)
         *    - Lightmap Encoding
         *    - Active Input Handling (Old/New/Both)
         *    - Auto Graphics API (can be set via SetUseDefaultGraphicsAPIs)
         *    - Graphics API ordering (can be set via SetGraphicsAPIs)
         *
         * 5. QUALITY SETTINGS
         *    - These are NOT part of PlayerSettings
         *    - Managed through QualitySettings class instead
         *
         * 6. ANDROID SPECIFIC (UI-ONLY)
         *    - Some Keystore Manager UI elements
         *    - Configuration dialog interactions
         *    - Some build settings UI elements
         *
         * 7. iOS SPECIFIC (UI-ONLY)
         *    - Some provisioning profile UI interactions
         *    - Capabilities checkboxes (require Xcode project modification)
         *    - Some entitlements (require post-build processing)
         *
         * 8. WEBGL SPECIFIC (UI-ONLY)
         *    - WebGL Template selection (can be set via code as string path)
         *    - Template preview
         *
         * 9. PUBLISHING SETTINGS (some)
         *    - Various store-specific metadata fields
         *    - Screenshots and promotional images
         *    - Store descriptions
         *
         * 10. BUILD SETTINGS
         *     - Build Profiles (separate from PlayerSettings)
         *     - Build Target selection (set during build, not in PlayerSettings)
         *
         * WORKAROUNDS:
         * - Icons: Use AssetDatabase and PlatformIcon API for programmatic icon assignment
         * - Splash Screens: Use SplashScreen API or modify project files directly
         * - Some settings: Can be modified via EditorPrefs or project files
         * - Post-build: Use IPostprocessBuildWithReport for build-time modifications
         *
         * NOTE: The Unity documentation states "You can use the PlayerSettings API
         * to control most of the settings available in this window." This means
         * some settings are intentionally UI-only.
         */
        #endregion

        #region READ-ONLY PROPERTIES
        /*
         * ===========================
         * READ-ONLY PROPERTIES
         * ===========================
         *
         * These properties can be READ but NOT SET via code:
         *
         * - PlayerSettings.productGUID (automatically generated)
         * - PlayerSettings.advancedLicense (license tier detection)
         * - PlayerSettings.Android.minSupportedSdkVersion (system minimum)
         *
         * These return information about the current state but cannot be modified.
         */

        public static void ReadOnlyExamples() {
            // READ-ONLY: Product GUID
            Guid productGuid = PlayerSettings.productGUID;
            Debug.Log($"Product GUID: {productGuid}");

            // READ-ONLY: Advanced License
            bool hasAdvanced = PlayerSettings.advancedLicense;
            Debug.Log($"Has Advanced License: {hasAdvanced}");

            // READ-ONLY: Android minimum supported SDK
            AndroidSdkVersions minSupported = PlayerSettings.Android.minSupportedSdkVersion;
            Debug.Log($"Min Supported Android SDK: {minSupported}");
        }
        #endregion
    }
}